// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMoviesApp.Data;

namespace MyMoviesApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210717120604_AddTypes")]
    partial class AddTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyMoviesApp.Models.Movie", b =>
                {
                    b.Property<int>("IdM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieTypeID")
                        .HasColumnType("int");

                    b.Property<string>("NameM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingM")
                        .HasColumnType("int");

                    b.Property<int>("YearM")
                        .HasColumnType("int");

                    b.Property<string>("statusM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdM");

                    b.HasIndex("MovieTypeID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MyMoviesApp.Models.MovieType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieTypes");
                });

            modelBuilder.Entity("MyMoviesApp.Models.Series", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieTypeId")
                        .HasColumnType("int");

                    b.Property<string>("NameS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingS")
                        .HasColumnType("int");

                    b.Property<int>("YearS")
                        .HasColumnType("int");

                    b.Property<string>("statusS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdS");

                    b.HasIndex("MovieTypeId");

                    b.ToTable("SeriesTV");
                });

            modelBuilder.Entity("MyMoviesApp.Models.Movie", b =>
                {
                    b.HasOne("MyMoviesApp.Models.MovieType", "MovieType")
                        .WithMany()
                        .HasForeignKey("MovieTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieType");
                });

            modelBuilder.Entity("MyMoviesApp.Models.Series", b =>
                {
                    b.HasOne("MyMoviesApp.Models.MovieType", "SeriesType")
                        .WithMany()
                        .HasForeignKey("MovieTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeriesType");
                });
#pragma warning restore 612, 618
        }
    }
}
